--- 
databases: 
  - 
    ipAllowList: []
    name: postgres
services: 
  - 
    buildCommand: ./bin/render-build.sh
    env: ruby
    envVars: 
      - 
        key: RAILS_MASTER_KEY
        sync: false
      - 
        fromDatabase: 
          name: postgres
          property: connectionString
        key: DATABASE_URL
    name: rails
    plan: free
    startCommand: "bundle exec rails s"
    type: web
  - 
    ipAllowList: []
    maxmemoryPolicy: noeviction
    name: redis
    plan: free
    type: redis
